### ISSUE TITLE
error when using run_bgc_dom_div.bash 

### ISSUE THREAD

**Issue by kazumaxneo** [pereiramemo/BiG-MEx#15]
Hello Emiliano.

run_bgc_dom_div.bash meta fails with following error messages,
Is there any solution ?

java -ea -Xmx198617m -cp /bioinfo/software/bbmap/current/ driver.FilterReadsByName in=/input/sample1-1.fq.gz in2=/input/sample1-2.fq.gz out=/scratch//out_dom_meta_div/redu_r1.fasta out2=/scratch//out_dom_meta_div/redu_r2.fasta names=/scratch//out_dom_meta_div/all_headers.list include=t overwrite=t
Executing driver.FilterReadsByName [in=/input/sample1-1.fq.gz, in2=/input/sample1-2.fq.gz, out=/scratch//out_dom_meta_div/redu_r1.fasta, out2=/scratch//out_dom_meta_div/redu_r2.fasta, names=/scratch//out_dom_meta_div/all_headers.list, include=t, overwrite=t]

Set INTERLEAVED to false
Exception in thread "main" java.lang.RuntimeException: Can't find file /input/sample1-1.fq.gz
at fileIO.ReadWrite.getRawInputStream(ReadWrite.java:880)
at fileIO.ReadWrite.getGZipInputStream(ReadWrite.java:973)
at fileIO.ReadWrite.getInputStream(ReadWrite.java:813)
at fileIO.FileFormat.getFirstOctet(FileFormat.java:407)
at stream.FASTQ.isInterleaved(FASTQ.java:126)
at stream.FastqReadInputStream.<init>(FastqReadInputStream.java:60)
at stream.ConcurrentReadInputStream.getReadInputStream(ConcurrentReadInputStream.java:119)
at stream.ConcurrentReadInputStream.getReadInputStream(ConcurrentReadInputStream.java:55)
at driver.FilterReadsByName.process(FilterReadsByName.java:256)
at driver.FilterReadsByName.main(FilterReadsByName.java:41)
filterbyname R1 and R2 failed

**Comment by pereiramemo** [comment]
Hi!

Could you please show me the command you used to run_bgc_dom_div.bash?

Thanks, 

Emiliano

**Comment by kazumaxneo** [comment]
Thanks for the reply. 

I tried your great tutorial. 
https://github.com/pereiramemo/BiG-MEx/wiki/Getting-started

#run run_bgc_dom_div.bash
sudo ../run_bgc_dom_div.bash meta metagenomic_samples/se_bgc_dom_osd2.gz metagenomic_samples/OSD2_R1_shotgun_workable.fastq.gz metagenomic_samples/OSD2_R2_shotgun_workable.fastq.gz metagenomic_samples/out_dom_div_osd2 --blast t --identity 0.5 --plot_tree t --only_rep t --coverage t --nslots 2 --verbose t --domains PKS_KS,PKS_AT

In the middle of the tutorial, I had run the above command without moving the previous output file, and got error.
So I moved the file to ${OUTPUT_DIR} as written in the tutorial like;
mv metagenomic_samples/out_dom_annot_osd2/se_bgc_dom.gz metagenomic_samples/se_bgc_dom_osd2.gz

And it works now.
Thank you so much for your help. Please close.

**Comment by pereiramemo** [comment]
Ok. Thanks for letting me know.
